name: Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
      - run: npm test
      - run: ls -al dist
      - run: npm run package:lin
      - run: ls -al dist
